### ISSUE TITLE
Hello Niall Douglas. I think std::exception .what() was a horrible mistake.

### ISSUE THREAD

**Issue by expnkx** [ned14/status-code#25]
std::exception in my opinion was a horrible mistake. exception.what() requires you to store extra data with an internal string which violates zero-overhead principle

Unfortunately, I think your library makes the same mistake again.

https://github.com/ned14/status-code/blob/a7dd7e3c0e967c9aeb881b7582a56ea2121d8712/include/win32_code.hpp#L154

error message should not report as a string (neither a c_str (std::exception .what() for example) nor a std::string, nor a string_ref) you are proposing here. It is not efficient. Exceptions should report to I/O stream direct instead of a string. That is also how OpenSSL reports errors.

The interface should be like:
virtual void report(error_reporter& report) = 0;
instead of
virtual string_ref name() const noexcept override { return string_ref("win32 domain"); }
The error should be directly reported to I/O device.

https://github.com/expnkx/fast_io/blob/dbb68b382af6ac90e34847b41b5622b2d5271a4f/include/fast_io_core_impl/fast_io_error.h#L113

https://github.com/expnkx/fast_io/blob/dbb68b382af6ac90e34847b41b5622b2d5271a4f/include/fast_io_hosted/platforms/win32_error.h#L40

All the tricks I did make allocation becomes minimal. Most of the time the errors will directly report in the I/O buffer. It mitigates allocation and copy. It also eliminates that extra string data member to store .what() string in the exception class.

**Comment by ned14** [comment]
I'm not sure what you're talking about here. A status code's textual message is just a string view onto data stored elsewhere. It couldn't be more efficient. We don't impose interfaces for serialising status codes because that's for end library users to decide. We don't need to say anything on that, because we provide a string view to some text, it's up to them how to combine that or format it. Indeed we don't even bring in `<iostream>` by default, it's only if you include that header do you get some iostream formatting printer overloads which do a bare minimum viable print of a status code.

As an example of how status code works, LLFIO defines a custom status code domain which carries additional payload in the status code, specifically the open handle which caused the failure. If, and only if, the status code departs that handle instance and it therefore might go out of scope, is the current path for that handle retrieved and stored. If at any point somebody wants to print the failure, then and only then is the message fetched and formatting done in order to generate a textual message.

As I'm sure you can see, if you handle failures locally, this is extremely efficient. Zero overhead.

If you handle failures close to locally, you pay a bit of overhead, but no more than is required for lifetime safety.

Only if you actually print or serialise, then and only then do you pay the costs of formatting, which typically involves lots of memory allocation and copying.

In the usual case, LLFIO never calls malloc at all. We have a ton of code here which requires that. So this approach definitely works, and works well.

**Comment by expnkx** [comment]
> I'm not sure what you're talking about here. A status code's textual message is just a string view onto data stored elsewhere. It couldn't be more efficient. We don't impose interfaces for serialising status codes because that's for end library users to decide. We don't need to say anything on that, because we provide a string view to some text, it's up to them how to combine that or format it. Indeed we don't even bring in `<iostream>` by default, it's only if you include that header do you get some iostream formatting printer overloads which do a bare minimum viable print of a status code.
> 
> As an example of how status code works, LLFIO defines a custom status code domain which carries additional payload in the status code, specifically the open handle which caused the failure. If, and only if, the status code departs that handle instance and it therefore might go out of scope, is the current path for that handle retrieved and stored. If at any point somebody wants to print the failure, then and only then is the message fetched and formatting done in order to generate a textual message.
> 
> As I'm sure you can see, if you handle failures locally, this is extremely efficient. Zero overhead.
> 
> If you handle failures close to locally, you pay a bit of overhead, but no more than is required for lifetime safety.
> 
> Only if you actually print or serialise, then and only then do you pay the costs of formatting, which typically involves lots of memory allocation and copying.
> 
> In the usual case, LLFIO never calls malloc at all. We have a ton of code here which requires that. So this approach definitely works, and works well.

Well. "Only if you actually print or serialise, then and only then do you pay the costs of formatting, which typically involves lots of memory allocation and copying."

No. It does do any extra memory allocation and copying. It actually does less allocation and copying.

1. When you abstract your code as a stream. All data will format in the I/O buffer itself.
2. It is extensive. You can directly report to std::string or a stream and the algorithm will your job efficiently.
3. It does not perform any extra copying.

The issue is that C++ iostream and C's stdio.h in general just suck. It does not provide a correct abstraction.

I believe your thoughts "it cannot be more efficient" is probably biased too. Just like people think charconv and fmtlib cannot be more efficient when it is completely proven untrue by my approaches.

Using string will also pay for a bunch of overhead.
1. string must allocate in some perform.
2. string cannot reuse the existing string's memory.
3. null terminator.
4. If your report your error as c_str(). Each time you use it will pay for an extra cost of strlen which is O(N).

fast_io::i/obuf_file | 0.04903s
std::to_chars+obuf_file | 0.12s


Look at reserve-write does.
https://github.com/expnkx/fast_io/blob/33a4660e5d08acfe1bd5c09a8909afdb832eda0a/include/fast_io_freestanding_impl/reserve_read_write.h#L65

1. it tries to "allocate" space on the stream's buffer. It checks whether stream's buffer has enough space, if it has, it will return the pptr() pointer. (which is true for 99% of cases)
2. If it does not have enough space:
It tries to see how much buffer size the algorithm requires:
if the buffer size <= 1024, it allocates on the stack. Run the algorithm and then write the array to the stream.
if it is larger than 1024, the stream will try to allocate a "string" by using the stream's allocator. take that allocator to create a string and then let the string take over of allocation which means we only have 1 allocation. Notice that this is the worse case scenario.

**Comment by expnkx** [comment]
The model can work and the stream is usually more efficient than any kind of string since its buffer is very large and fixed. No more allocation. No more cache or TLB misses for stream since its buffer size is fixed.

The problem is that iostream is extremely slow, does not provide correct abstraction and it does not work in a freestanding environment. I would like to design some kind of "io" stream in a freestanding environment without an operating system.

I also hacked FILE*, string and iostream's internal implementations to make the formatting directly on the string or stream's buffer.
FILE*:
https://github.com/expnkx/fast_io/tree/master/include/fast_io_legacy_impl/c
iostream:
https://github.com/expnkx/fast_io/tree/master/include/fast_io_legacy_impl/cpp
string:
https://github.com/expnkx/fast_io/blob/master/include/fast_io_freestanding_impl/string/libstdc%2B%2B.h
